apiVersion: v1
kind: Service
metadata:
  name: apartments
  labels:
    app: apartments
spec:
  type: NodePort
  ports:
  - name: server
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: apartments